# Generated by Django 3.2 on 2021-08-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
